-- Active: 1690793481131@@127.0.0.1@5432@okanban@public


DROP TABLE IF EXISTS "card_has_tag";
DROP TABLE IF EXISTS "card";
DROP TABLE IF EXISTS "tag";
DROP TABLE IF EXISTS "list";

CREATE TABLE "list"(
    id SERIAL PRIMARY KEY NOT NULL UNIQUE,
    title TEXT NOT NULL,
    position INTEGER DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP
);

CREATE TABLE "card"(
    id SERIAL PRIMARY KEY NOT NULL UNIQUE,
    content TEXT NOT NULL,
    position INTEGER DEFAULT 0,
    color TEXT,
    list_id INT REFERENCES list("id") ON DELETE CASCADE,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP
);


CREATE TABLE "tag"(
    id SERIAL PRIMARY KEY NOT NULL UNIQUE,
    name TEXT NOT NULL UNIQUE,
    color TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP
);

CREATE TABLE "card_has_tag"(
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    card_id INT REFERENCES card("id") ON DELETE CASCADE,
    tag_id INT REFERENCES tag("id") ON DELETE CASCADE,
    UNIQUE("card_id", "tag_id"),
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ
);
